version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser", "nodejs"]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true
